apiVersion: v1
kind: ConfigMap
metadata:
  name: upbound-crossplane-versions
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  crossplaneVersion: {{ (trimPrefix "v" .Values.uxp.image.tag) }}
  uxpVersion: {{ .Chart.Version }}
  {{- range .Chart.Dependencies }}
    {{- if eq .Alias "upbound" }}
  upboundControllerManagerVersion: {{ .Version | quote }}
    {{- else if eq .Alias "webui" }}
  webUIVersion: {{ .Version | quote }}
    {{- else if eq .Alias "apollo" }}
  apolloVersion: {{ .Version | quote }}
    {{- end }}
  {{- end }}